-- AlterTable
ALTER TABLE `users` ADD COLUMN `averageScore` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `badges` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `level` INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN `points` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `quizzes` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `streak` INTEGER NOT NULL DEFAULT 0;
